'use strict';

// Each item: { topic, passage?, prompt, choices: [4 strings], correct: 'A'|'B'|'C'|'D', explanation }
// Topics: information-ideas | craft-structure | expression-ideas | standard-conventions

module.exports = [

  // ===== STANDARD ENGLISH CONVENTIONS =====
  {
    topic: 'standard-conventions',
    prompt: 'Which choice conforms to the conventions of Standard English?\n\n"The collection of rare coins ____ displayed in the museum\'s east wing."',
    choices: ['are', 'is', 'were', 'have been'],
    correct: 'B',
    explanation: 'The subject is "collection" (singular). A singular subject takes the singular verb "is."',
  },
  {
    topic: 'standard-conventions',
    prompt: 'Which choice conforms to the conventions of Standard English?\n\n"Neither the teacher nor the students ____ aware of the schedule change."',
    choices: ['was', 'were', 'is', 'has been'],
    correct: 'B',
    explanation: 'With "neither/nor," the verb agrees with the nearer subject "students" (plural), so "were" is correct.',
  },
  {
    topic: 'standard-conventions',
    prompt: 'Which choice conforms to the conventions of Standard English?\n\n"Each of the runners ____ given a numbered bib before the race."',
    choices: ['were', 'are', 'was', 'have been'],
    correct: 'C',
    explanation: '"Each" is singular and takes a singular verb: "was."',
  },
  {
    topic: 'standard-conventions',
    prompt: 'Which choice correctly punctuates the sentence?\n\n"Maria packed three items for the trip ____ a map, a compass, and a water bottle."',
    choices: [', that is', ': a map', ':', '— that is'],
    correct: 'C',
    explanation: 'A colon introduces a list after a complete clause.',
  },
  {
    topic: 'standard-conventions',
    prompt: 'Which choice correctly joins the two independent clauses?\n\n"The experiment failed twice ____ the team refused to give up."',
    choices: [', but', ' but', '; but', ', and but'],
    correct: 'A',
    explanation: 'Two independent clauses joined by "but" require a comma before the conjunction: ", but."',
  },
  {
    topic: 'standard-conventions',
    prompt: 'Which choice correctly punctuates the sentence?\n\n"My favorite author ____ whose novels I reread every summer ____ will speak at the library."',
    choices: [', / ,', ': / :', '( / )', '; / ;'],
    correct: 'A',
    explanation: 'The nonessential clause "whose novels I reread every summer" is set off with a pair of commas.',
  },
  {
    topic: 'standard-conventions',
    prompt: 'Which choice correctly completes the sentence?\n\n"The storm knocked out power across the city ____ thousands of homes went dark within minutes."',
    choices: [', ', '; ', ' and so, ', ': however '],
    correct: 'B',
    explanation: 'Both parts are independent clauses with no conjunction. A semicolon correctly links them.',
  },
  {
    topic: 'standard-conventions',
    prompt: 'Which choice conforms to the conventions of Standard English?\n\n"By the time the guests arrived, the chef ____ the meal."',
    choices: ['has prepared', 'had prepared', 'prepares', 'will prepare'],
    correct: 'B',
    explanation: 'The past perfect "had prepared" shows an action completed before another past action.',
  },
  {
    topic: 'standard-conventions',
    prompt: 'Which choice conforms to the conventions of Standard English?\n\n"If she ____ earlier, she would have caught the train."',
    choices: ['leaves', 'left', 'had left', 'has left'],
    correct: 'C',
    explanation: 'A past unreal conditional uses "had left" in the if-clause to match "would have caught."',
  },
  {
    topic: 'standard-conventions',
    prompt: 'Which choice conforms to the conventions of Standard English?\n\n"The committee announced ____ decision after a long debate."',
    choices: ['their', 'they\'re', 'its', 'it\'s'],
    correct: 'C',
    explanation: '"Committee" is a singular collective noun. The singular possessive "its" is correct.',
  },
  {
    topic: 'standard-conventions',
    prompt: 'Which choice conforms to the conventions of Standard English?\n\n"When a student studies consistently, ____ tends to perform better on exams."',
    choices: ['they', 'he or she', 'them', 'you'],
    correct: 'B',
    explanation: 'The singular antecedent "a student" requires the singular pronoun "he or she."',
  },
  {
    topic: 'standard-conventions',
    prompt: 'Which choice corrects the misplaced modifier?\n\n"Walking through the forest, ____."',
    choices: ['the tall trees amazed us', 'we were amazed by the tall trees', 'the trees were amazing', 'amazement filled the air'],
    correct: 'B',
    explanation: '"Walking through the forest" must describe the people doing the walking, "we."',
  },
  {
    topic: 'standard-conventions',
    prompt: 'Which choice correctly completes the sentence?\n\n"There are fewer ____ in the recipe than I expected."',
    choices: ['ingredients', 'ingredient', 'amounts', 'quantity'],
    correct: 'A',
    explanation: '"Fewer" is used with countable plural nouns: "ingredients."',
  },
  {
    topic: 'standard-conventions',
    prompt: 'Which choice conforms to the conventions of Standard English?\n\n"Between you and ____, the surprise party is next Friday."',
    choices: ['I', 'me', 'myself', 'mine'],
    correct: 'B',
    explanation: 'After the preposition "between," the objective pronoun "me" is required.',
  },
  {
    topic: 'standard-conventions',
    prompt: 'Which choice correctly punctuates the sentence?\n\n"After months of training ____ the athlete finally qualified for the national team."',
    choices: [', ', '; ', ': ', ' — and'],
    correct: 'A',
    explanation: 'An introductory phrase is followed by a comma.',
  },
  {
    topic: 'standard-conventions',
    prompt: 'Which choice maintains parallel structure?\n\n"The coach told the team to practice daily, to eat well, and ____."',
    choices: ['getting enough sleep', 'they should sleep enough', 'to get enough sleep', 'enough sleep matters'],
    correct: 'C',
    explanation: 'The list uses "to practice," "to eat," so the third item must be "to get enough sleep."',
  },
  {
    topic: 'standard-conventions',
    prompt: 'Which choice conforms to the conventions of Standard English?\n\n"Of the two routes, the coastal road is ____."',
    choices: ['the most scenic', 'more scenic', 'most scenic', 'scenicest'],
    correct: 'B',
    explanation: 'When comparing exactly two things, use the comparative form: "more scenic."',
  },
  {
    topic: 'standard-conventions',
    prompt: 'Which choice conforms to the conventions of Standard English?\n\n"The data ____ that temperatures have risen since 1950."',
    choices: ['suggests', 'suggest', 'suggesting', 'to suggest'],
    correct: 'B',
    explanation: 'In formal usage "data" is treated as plural, taking the plural verb "suggest."',
  },
  {
    topic: 'standard-conventions',
    prompt: 'Which choice correctly completes the sentence?\n\n"The library extended ____ hours during final exams."',
    choices: ['it\'s', 'its', 'its\'', 'their'],
    correct: 'B',
    explanation: '"Its" is the singular possessive pronoun; "it\'s" would mean "it is."',
  },

  // ===== EXPRESSION OF IDEAS =====
  {
    topic: 'expression-ideas',
    prompt: 'Which transition best fits the blank?\n\n"The new policy reduced waiting times. ____, several patients reported feeling rushed during appointments."',
    choices: ['Therefore', 'However', 'Likewise', 'For example'],
    correct: 'B',
    explanation: 'The second sentence presents a contrast to the improvement, so "However" fits.',
  },
  {
    topic: 'expression-ideas',
    prompt: 'Which transition best fits the blank?\n\n"Solar panels are now cheaper than ever. ____, installation rates have risen sharply."',
    choices: ['Nevertheless', 'In contrast', 'As a result', 'Otherwise'],
    correct: 'C',
    explanation: 'Rising installation rates are a consequence of cheaper panels: "As a result."',
  },
  {
    topic: 'expression-ideas',
    prompt: 'Which transition best fits the blank?\n\n"The first draft was disorganized. ____, the editor decided to rewrite it entirely."',
    choices: ['Consequently', 'For instance', 'In addition', 'Similarly'],
    correct: 'A',
    explanation: 'The editor\'s decision results from the draft\'s problems: "Consequently."',
  },
  {
    topic: 'expression-ideas',
    prompt: 'Which transition best fits the blank?\n\n"The museum offers free admission on weekdays. ____, it hosts guided tours twice each afternoon."',
    choices: ['However', 'In addition', 'Therefore', 'Instead'],
    correct: 'B',
    explanation: 'The sentence adds another offering: "In addition."',
  },
  {
    topic: 'expression-ideas',
    prompt: 'Which transition best fits the blank?\n\n"The bridge was scheduled to open in May. ____, construction delays pushed the opening to September."',
    choices: ['Similarly', 'However', 'Therefore', 'For example'],
    correct: 'B',
    explanation: 'The actual opening contradicts the schedule: "However."',
  },
  {
    topic: 'expression-ideas',
    prompt: 'Which choice best expresses the idea concisely?',
    choices: [
      'Due to the fact that it was raining, the game was postponed.',
      'Because it was raining, the game was postponed.',
      'On account of the rainy weather conditions, the game was postponed.',
      'The game, because of rain that was falling, was postponed.',
    ],
    correct: 'B',
    explanation: '"Because it was raining" conveys the cause most concisely.',
  },
  {
    topic: 'expression-ideas',
    prompt: 'Which choice best maintains a formal tone for an academic essay?',
    choices: [
      'The results were totally awesome and blew everyone away.',
      'The results were super surprising to the researchers.',
      'The results were unexpected and prompted further study.',
      'The results kind of shocked the whole team.',
    ],
    correct: 'C',
    explanation: 'Choice C uses precise, formal language. The others are too casual.',
  },
  {
    topic: 'expression-ideas',
    prompt: 'Which choice best combines the two sentences?\n\n"The lecture was long. It held the audience\'s attention throughout."',
    choices: [
      'The lecture was long, and it held attention throughout.',
      'Although the lecture was long, it held the audience\'s attention throughout.',
      'The lecture was long it held the audience\'s attention throughout.',
      'The lecture was long, it held the audience\'s attention throughout.',
    ],
    correct: 'B',
    explanation: '"Although" signals the contrast between the lecture\'s length and its ability to hold attention.',
  },

  // ===== CRAFT & STRUCTURE =====
  {
    topic: 'craft-structure',
    passage: 'Although the river appeared calm on the surface, the current beneath was deceptively powerful, pulling debris swiftly downstream.',
    prompt: 'As used in the sentence, "deceptively" most nearly means',
    choices: ['honestly', 'misleadingly', 'obviously', 'gently'],
    correct: 'B',
    explanation: 'The surface looked calm but the current was powerful — appearances were misleading.',
  },
  {
    topic: 'craft-structure',
    passage: 'The scientist was meticulous in her work, recording every measurement twice and double-checking each calculation.',
    prompt: 'As used in the sentence, "meticulous" most nearly means',
    choices: ['careless', 'careful', 'hurried', 'reluctant'],
    correct: 'B',
    explanation: 'Recording twice and double-checking shows great care: "meticulous" means careful and precise.',
  },
  {
    topic: 'craft-structure',
    passage: 'Critics praised the novel for its candid portrayal of family conflict, noting that the author held nothing back.',
    prompt: 'As used in the sentence, "candid" most nearly means',
    choices: ['dishonest', 'frank', 'cautious', 'cheerful'],
    correct: 'B',
    explanation: 'The author "held nothing back," indicating openness. "Candid" means frank.',
  },
  {
    topic: 'craft-structure',
    passage: 'The negotiations reached an impasse when neither side was willing to compromise.',
    prompt: 'As used in the sentence, "impasse" most nearly means',
    choices: ['agreement', 'deadlock', 'celebration', 'beginning'],
    correct: 'B',
    explanation: 'Neither side would compromise, so talks were stuck. An "impasse" is a deadlock.',
  },
  {
    topic: 'craft-structure',
    passage: 'Her arguments were so cogent that even her opponents conceded the strength of her reasoning.',
    prompt: 'As used in the sentence, "cogent" most nearly means',
    choices: ['confusing', 'convincing', 'lengthy', 'emotional'],
    correct: 'B',
    explanation: 'Opponents conceded her reasoning\'s strength, so "cogent" means convincing.',
  },
  {
    topic: 'craft-structure',
    passage: 'The ancient aqueducts of Rome were engineering marvels, transporting water across great distances using only gravity.',
    prompt: 'As used in the passage, "marvels" most nearly means',
    choices: ['failures', 'wonders', 'ruins', 'mysteries'],
    correct: 'B',
    explanation: 'Praised for impressive engineering, "marvels" means wonders or impressive achievements.',
  },

  // ===== INFORMATION & IDEAS =====
  {
    topic: 'information-ideas',
    passage: 'Honeybees communicate the location of food through a "waggle dance." The angle of the dance relative to the sun indicates direction, while the duration signals distance. Bees adjust the dance as the sun moves, demonstrating a remarkable internal sense of time.',
    prompt: 'Which choice best states the main idea of the passage?',
    choices: [
      'Honeybees prefer food sources that are close to the hive.',
      'Honeybees use a precise dance to convey the direction and distance of food.',
      'The sun is the most important factor in a bee\'s daily life.',
      'Researchers disagree about how bees find food.',
    ],
    correct: 'B',
    explanation: 'The passage explains how the waggle dance encodes direction and distance.',
  },
  {
    topic: 'information-ideas',
    passage: 'Early photographers faced a major obstacle: exposure times could last several minutes. Subjects had to remain perfectly still, which is why people in nineteenth-century portraits rarely smile.',
    prompt: 'The main purpose of the passage is to',
    choices: [
      'argue that early photographs are more valuable than modern ones',
      'explain why subjects in early photographs appear serious',
      'describe the chemistry of early photographic film',
      'compare photography to portrait painting',
    ],
    correct: 'B',
    explanation: 'The passage connects long exposure times to the lack of smiling.',
  },
  {
    topic: 'information-ideas',
    passage: 'Urban gardens do more than provide fresh produce. They cool neighborhoods by shading pavement, absorb rainwater, and offer habitat for pollinators. For many city residents, they also create rare spaces for community gathering.',
    prompt: 'Which choice best describes the function of the passage?',
    choices: [
      'It lists several benefits of urban gardens beyond growing food.',
      'It argues that cities should ban concrete pavement.',
      'It explains how to start a garden in a small space.',
      'It compares urban gardens with rural farms.',
    ],
    correct: 'A',
    explanation: 'The passage enumerates multiple benefits: cooling, drainage, habitat, community.',
  },
  {
    topic: 'information-ideas',
    passage: 'A study tracked two groups of students. The group that took handwritten notes scored higher on conceptual questions than the group that typed notes, even though typists recorded more words.',
    prompt: 'Which finding, if true, would most strongly support the idea that handwriting aids understanding?',
    choices: [
      'Typists finished their notes faster than handwriters.',
      'Handwriters rephrased ideas in their own words more often than typists.',
      'Both groups enjoyed the lectures equally.',
      'Typists used laptops with larger screens.',
    ],
    correct: 'B',
    explanation: 'Rephrasing in one\'s own words reflects deeper processing, explaining why handwriters understood concepts better.',
  },
  {
    topic: 'information-ideas',
    passage: 'Proponents claim a four-day workweek increases productivity. They point to a company trial in which weekly output stayed the same even though employees worked one fewer day.',
    prompt: 'Which detail best supports the proponents\' claim?',
    choices: [
      'Employees worked one fewer day per week.',
      'Weekly output stayed the same despite fewer working hours.',
      'The trial was conducted at a single company.',
      'The workweek was reduced to four days.',
    ],
    correct: 'B',
    explanation: 'Maintaining the same output with fewer hours is the evidence that productivity per hour rose.',
  },
  {
    topic: 'information-ideas',
    passage: 'The café was usually bustling by eight in the morning, but today the chairs remained stacked on the tables and the lights stayed off well past nine.',
    prompt: 'Which choice is best supported by the passage?',
    choices: [
      'The café had become more popular than ever.',
      'The café did not open at its usual time.',
      'The café had permanently closed.',
      'The café served breakfast only on weekends.',
    ],
    correct: 'B',
    explanation: 'Stacked chairs and lights off past the usual hour suggest the café had not opened on time.',
  },
  {
    topic: 'information-ideas',
    passage: 'Despite receiving the highest score on the entrance exam, Daniel hesitated before accepting the scholarship, asking the committee for a week to consider his options.',
    prompt: 'Which choice is best supported by the passage?',
    choices: [
      'Daniel was uncertain about whether to accept the scholarship.',
      'Daniel had failed the entrance exam.',
      'Daniel had already enrolled in another school.',
      'Daniel was not offered the scholarship.',
    ],
    correct: 'A',
    explanation: 'Hesitating and asking for time indicates uncertainty.',
  },
  {
    topic: 'information-ideas',
    passage: 'Volunteers spent the weekend restoring the wetland, removing invasive plants and replanting native grasses to revive the local ecosystem.',
    prompt: 'Which choice best states the purpose of the volunteers\' work?',
    choices: [
      'to build a new park for visitors',
      'to restore the health of a natural habitat',
      'to study invasive plant species',
      'to create farmland from the wetland',
    ],
    correct: 'B',
    explanation: 'Removing invasive species and replanting natives to "revive the ecosystem" shows the goal was habitat restoration.',
  },
  {
    topic: 'information-ideas',
    passage: 'The documentary did not shy away from controversy; it presented opposing viewpoints side by side and let viewers weigh the evidence themselves.',
    prompt: 'The passage suggests that the documentary was',
    choices: ['one-sided', 'balanced', 'humorous', 'poorly made'],
    correct: 'B',
    explanation: 'Presenting opposing viewpoints and letting viewers decide indicates a balanced approach.',
  },
];
